pipeline {
    agent {
        label 'AGENT-1'
    }
    options{
        timeout(time: 10, unit: 'Minutes')
        disableConcurrentBuilds()  // 
        //retry(1)  // if the job fails it will retry to run the job again specified no of times
    }
    environment{
        DEBUG = 'true'
    }
    parameters{
        string(name: 'PERSON', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')
        text(name: 'BIOGRAPHY', defaultValue: '', description: 'Enter some information about the person')
        booleanParam(name: 'TOGGLE', defaultValue: true, description: 'Toggle this value')
        choice(name: 'CHOICE', choices: ['One', 'Two', 'Three'], description: 'Pick something')
        password(name: 'PASSWORD', defaultValue: 'SECRET', description: 'Enter a password')
    }
    stages {
        stage('Build'){
            steps {
                sh 'echo this is build'
            }
        }
        stage('Test'){
            steps{
                sh 'echo this is test'
            }
        }
        stage('Deploy'){
            when {
                expression {env.GIT_BRANCH != "origin/main"}
            } 
        }
            steps{
                sh 'echo This is deploy'
            }
        stage('print params'){
            steps{
                echo " Hello $(params.PERSON)"
                echo "Biography: $(params.BIOGRAPHY)"
                echo "toggle: $(params.TOGGLE)"
                echo " Choise: $(params.CHOISE)"
                echo " Password: $(params.PASSWORD)"
            }
        }
    }
    post{
        always{
            echo "This section runs always"
            deleteDir()
        }
        success{
            echo "This section runs when pipeline success"
        }
        failure{
            echo " This section runs when pipeline failure"
        }
    }
}   